### ISSUE TITLE
La nueva versión atributos?

### ISSUE THREAD

**Issue by rexp2** [luuuis/hass_omie#20]
Hola de nuevo,  con la nueva versión el atributo "day_hours " ha cambiado por "today_hours " pero ahora muestra la fecha y ya los sensores que dependen de estos valores han dejado de funcionar.  Como puedo resolverlo?

**Comment by luuuis** [comment]
Tenta assim:

```
  - platform: template
    sensors:
      coste_diario_vertido:
        friendly_name: "Vertido diario electricidad"
        unit_of_measurement: "€"
        value_template: |
          {% set ns = namespace(horas=[]) %}
          {% for dt, precio in state_attr('sensor.omie_spot_price_pt', 'today_hours').items() %}
            {% set vertido = states('sensor.balance_vertido' ~ ('%02d' % dt.hour)) | float %}
            {% set ns.horas = ns.horas + [vertido * precio] %}
          {% endfor %}
          {{ ns.horas | sum | round(3) }}
```

**Comment by rexp2** [comment]
Es que he creado una serie de sensores derivados de tu integración y si el atributo muestra la fecha actual podría poner los atributos hoy pero mañana ya no servirían. Te pongo uno de los sensores que he creado a partir de los atributos de Omie para expresarme mejor:

- platform: template
    sensors:    
      precioomie:
        friendly_name: "Precio Omie"
        unit_of_measurement: €
        value_template: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[states('sensor.formatohsinh')|int]|float / 1000)|round(5)}}"
        attribute_templates:
          0: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[0]|float / 1000)|round(5)}}"
          1: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[1]|float / 1000)|round(5)}}"
          2: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[2]|float / 1000)|round(5)}}"
          3: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[3]|float / 1000)|round(5)}}"
          4: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[4]|float / 1000)|round(5)}}"
          5: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[5]|float / 1000)|round(5)}}"
          6: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[6]|float / 1000)|round(5)}}"
          7: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[7]|float / 1000)|round(5)}}"
          8: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[8]|float / 1000)|round(5)}}"
          9: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[9]|float / 1000)|round(5)}}"
          10: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[10]|float / 1000)|round(5)}}"
          11: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[11]|float / 1000)|round(5)}}"
          12: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[12]|float / 1000)|round(5)}}"
          13: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[13]|float / 1000)|round(5)}}"
          14: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[14]|float / 1000)|round(5)}}"
          15: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[15]|float / 1000)|round(5)}}"
          16: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[16]|float / 1000)|round(5)}}"
          17: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[17]|float / 1000)|round(5)}}"
          18: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[18]|float / 1000)|round(5)}}"
          19: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[19]|float / 1000)|round(5)}}"
          20: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[20]|float / 1000)|round(5)}}"
          21: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[21]|float / 1000)|round(5)}}"
          22: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[22]|float / 1000)|round(5)}}"
          23: "{{(state_attr('sensor.omie_spot_price_es', 'day_hours')[23]|float / 1000)|round(5)}}"

**Comment by rexp2** [comment]
Mi sugerencia es que en lugar de poner la fecha completa en el atributo today_hours solo pusiera la hora:
00: 67.60
01: 80.90
02: 87.34
Etc
De esa manera podría actualizar sin problemas. Así he tenido que volver a la versión anterior.

**Comment by rexp2** [comment]
Otro sensor que me hace una previsión de la media de venta omie dependiendo de las horas de sol que son diferentes cada mes:

      prevmediaventaomie:
        friendly_name: "Prev.Omie Media Venta"
        unit_of_measurement: "€"
        icon_template: mdi:clipboard-pulse-outline
        value_template: >          
          {% if is_state('sensor.formatomes', '12') or is_state('sensor.formatomes', '1') %}
            {{ ((state_attr('sensor.omie_spot_price_es', 'day_hours')[9:16] | map('int') | sum / states('sensor.horasdeventa')|float)|float / 1000) | round(3) }}
          {% elif is_state('sensor.formatomes', '11') or is_state('sensor.formatomes', '2') %}
            {{ ((state_attr('sensor.omie_spot_price_es', 'day_hours')[9:17] | map('int') | sum / states('sensor.horasdeventa')|float)|float / 1000) | round(3) }}
          {% elif is_state('sensor.formatomes', '10') or is_state('sensor.formatomes', '3') %}
            {{ ((state_attr('sensor.omie_spot_price_es', 'day_hours')[9:18] | map('int') | sum / states('sensor.horasdeventa')|float)|float / 1000) | round(3) }}
          {% else %}
            {{ ((state_attr('sensor.omie_spot_price_es', 'day_hours')[9:19] | map('int') | sum / states('sensor.horasdeventa')|float)|float / 1000) | round(3) }}
          {% endif %}

Todos estos sensores no pueden funcionar con la nueva versión.

**Comment by luuuis** [comment]
> Todos estos sensores no pueden funcionar con la nueva versión.

Não há nada que consigas fazer na versão anterior que não consegues fazer na nova versão, é só necessário saber trabalhar com os templates [jinja2](https://jinja.palletsprojects.com/en/2.10.x/templates/) para se conseguir adaptar. :)

O `today_hours` contém um Python [`dict`](https://docs.python.org/3.9/tutorial/datastructures.html#dictionaries) com a hora e preço, mais ou menos assim:
```
# atributos do sensor
{
  'today_hours': {
    '2023-05-11T00:00:00+01:00': 96.94,
    ...
  }
}
```

A "chave" do dict identifica a hora de forma inequívoca independentemente do fuso horário, que pode ser [CET](https://www.timeanddate.com/time/zones/cet) (Espanha), [WET](https://www.timeanddate.com/time/zones/wet) (Portugal, Las Palmas), [AZOT](https://www.timeanddate.com/time/zones/azot) (Açores) ou outros. Além disso, facilita o tratamento correcto dos dias de mudança [DST](https://www.timeanddate.com/time/dst/): 26 de Março (dia que tem 23 horas: 0, 1, 3, 4, ..., 23) e 29 de Outubro (dia que tem 25 horas: 0, 1, 2, 2, 3, ..., 23).

Os teus templates têm essa falha e sobretudo muita repetição desnecessária, no entanto para manter tudo organizado da forma como está podes simplesmente descartar a informação da hora local, ficando com uma lista de preços. Para fazer isso basta substituir

```
state_attr('sensor.omie_spot_price_es', 'day_hours')
```

por

```
state_attr('sensor.omie_spot_price_es', 'today_hours').values() | list
```

em todos os templates. 👍

**Comment by rexp2** [comment]
Lo intentaré, muchas gracias
