### ISSUE TITLE
[Fix] Correcção à TAR em tarifa simples hora a hora

### ISSUE THREAD

**Issue by renatose** [luuuis/hass_omie#21]
Ver o [diff do meu fork](https://github.com/renatose/hass_omie/wiki/Coop%C3%A9rnico-Base-Simples-hora-a-hora/_compare/e7eb7e55648b0785fe15a5a291c276ea6c24e89f...e239e4c96303db53314055619417111c3358492a?diff=split), que é auto-explicatório.

**Comment by luuuis** [comment]
Corrigido, obrigado. Resultado de muito copy-paste... 😊
