### ISSUE TITLE
Tomorrow Null

### ISSUE THREAD

**Issue by jsantosdias** [luuuis/hass_omie#23]
Boa tarde!
Não sei se está a acontecer com mais alguém, mas hoje não tenho valores tomorrow. Estão todos null, seja para Portugal ou para Espanha... Que se passará?

**Comment by jsantosdias** [comment]
Recarreguei o dispositivo várias vezes, mas nunca consegui... Agora reiniciei o HASS e funcionou... Não sei que problema será... A ver se não se repete...

**Comment by luuuis** [comment]
Activa o nível DEBUG nos logs para se conseguir investigar no caso de voltar a acontecer.

```
logger:
  logs:
    custom_components.omie: debug
```
