### ISSUE TITLE
Valor venda inedxado

### ISSUE THREAD

**Issue by codedmind** [luuuis/hass_omie#24]
Os valores de venda indexados não deveria ser com alteração horária?
Na Suelectricidade é indicado que a formula de calculo varia consoante o horario em que é injectado na rede.

`De acordo com o número 5, do artigo 288º, do Decreto-lei n.º 15/2022, de 14 de janeiro, o preço do kWh está indexado ao preço do mercado horário do Operador de Mercado Ibérico (OMIE). Esse preço varia todas as horas.
`
https://sueletricidade.pt/pt-pt/complex-pages/2081/facilitador-de-mercado

**Comment by luuuis** [comment]
Uns comercializadores usam o valor horário e outros a média diária. É conforme contratualizado entre produtor e comprador.

Parece que a SUElectricidade, por ser o CUR, tem de remunerar segundo esse DL sim.
