### ISSUE TITLE
Hora (GMT / GMT+1 / GMT + DSV)

### ISSUE THREAD

**Issue by r-amado** [luuuis/hass_omie#25]
Boa noite,
![image](https://github.com/luuuis/hass_omie/assets/89645023/25694609-603f-4a78-ae37-e1a4393e9ea8)
@luuuis já tocámos neste tema, mas gostava de explorar mais o tema, dado que o sensor da hora atual parece estar a indicar a hora à frente. 
O print acima mostra o valor do sensor sensor.omie_spot_price_pt às 21h33 com o valor de 96,56, quando no site da omip (omipdata), indica esse valor para o período 22h-23h.

Nos atributos este valor está associado à data. +01:00.
Hora na verdade a hora portuguesa atualmente é GMT+0 + DSV, e creio ser esse o problema, porque o meu HomeAssistant está no timezone Lisbon (GMT+0) e detecta que estamos com DSV=1, o que faz com que embora sejam 20:33 (GMT+0), na verdade com DSV=1 (período de verão) são 21h33. 

Hora o sensor está a usar GMT+1, como se vê nos atributos, e o sensor está a devolver o valor para a hora seguinte, e não da hora corrente.
![image](https://github.com/luuuis/hass_omie/assets/89645023/bd10ec55-af86-4c54-9724-95088339cc4e)

Disponivel para tentar perceber como dar a volta ao tema e eventualmente ajudar.
Após este tema ser "resolvido", publico o sensor de trihorário para a Coopernico (que estou a usar). 
Obrigado mais uma vez pelo trabalho desenvolvido!

**Comment by jsantosdias** [comment]
O valor que aparece no site omie é sempre hora espanhola. Às 22h de espanha, são 21h portuguesas... É esse o valor que a Coopérnico tem em conta para o seu tarifário... Nalguns gráficos até aparece em ordenação de horas: a 1ª, 2ª, que em Portugal será 23h...

**Comment by r-amado** [comment]
Mas o valor que mostrei com a tabela lateral é do site omip e não do site omie. Creio que a Coopernico se baseia no horário e preço marginal da OMIP, logo da hora portuguesa. Ou não?

**Comment by luuuis** [comment]
Viva,

O valor é o correcto para essa hora e a tua imagem confirma-o.

Conforme discutido anteriormente nos vários fóruns/redes (mas acho que ainda não aqui no GitHub por isso obrigado por trazeres este tema para aqui) a hora do OMIE refere-se ao fuso horário CET. Isso é muito claro no site deles e também já me foi confirmado pela Coopérnico e ainda directamente pelo OMIE a outro utilizador do grupo Autoconsumo Fotovoltaico.

<img width="400" src="https://github.com/luuuis/hass_omie/assets/161006/0f39aba5-be34-4ff3-8e69-07abfdca1ebf"/>

Ora, o valor `2023-06-06T21:00:00+0100` designa as 21 horas do dia de hoje no fuso horário de Portugal. O "desvio" de `+0100` é relativo ao UTC, um fuso horário que não aplica DST (horário de verão). Não é GMT+1, é UTC+1. No horário de verão em Portugal (excluindo Açores) será sempre UTC+1 e no horário de inverno aí sim UTC+0.

Só para martelar o mesmo ponto, estas horas representam exactamente o mesmo instante e o valor para todas é o tal `96,56`.
- Açores: `2023-06-06T20:00:00+0000`
- Portugal: `2023-06-06T21:00:00+0100`
- Espanha: `2023-06-06T22:00:00+0200`

Podes ler mais sobre o formato [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) pela net fora. Eu apresento as horas neste formato precisamente para evitar os equívocos causados por escrever só `1` ou `21` sem o contexto adicional do fuso horário.

Se não estiveres convencido ou se tiveres alguma dúvida diz pois sei que fusos horários é um tema que tem tendência a gerar confusão e assim fica já aqui a informação para outros que possam vir a ter as mesmas dúvidas.

**Comment by r-amado** [comment]
Ajuda-me aqui então a perceber a informação partilhada no site OMIP e OMIE, para a hora atual (22h49 - 06/06/2023)
![image](https://github.com/luuuis/hass_omie/assets/89645023/28b68e1e-36f8-43bd-8673-77c7e9c86d8d)

**Comment by luuuis** [comment]
A hora actual **em Espanha** no momento em que escreveste o comentário eram 23:49 por isso no gráfico da direita terias de consultar a **coluna 24** (a última hora do dia) porque a hora OMIE conta a partir de 1 e não de 0 como seria de esperar.

Como estás em Portugal deves antes consultar a coluna 23, a penúltima. Idem para a imagem da esquerda (é a penúltima linha) pela mesma lógica.

**Comment by r-amado** [comment]
@luuuis de acordo com o tooltip/modal que apresentaste indica que todos os valores apresentados são referentes a períodos como indicas. em que o período 1 refere-se a 00:00 a 01:00 CET.
Devo estar a fazer confusão, ou da hora tardia estou a dar um nó no cérebro.
O que dizes faz sentido, mas então os valores dos preços marginais ES e PT no sensor não deveriam ter o mesmo valor, porque se o coordinator.py e o sensor.py utilizam a hora local do HomeAssistant, então neste momento deveria ter 89,99 para Portugal e 83 para Espanha. Não?

**Comment by luuuis** [comment]
@r-amado desculpa, eu é que te induzi em erro com o meu comentário anterior. 🤦 O valor tem de ser visto sempre na coluna do horário Espanhol, nada de saltar para a coluna do lado só porque estás em PT.

Vejamos, agora já são 23 em Portugal e 00 do dia 7 de Junho em Espanha. Logo, importa consultar a coluna 1 do dia 7. Se são 00 no fuso horário de referência é aí que temos obrigatoriamente de encontrar o nosso valor.

<img width="400" src="https://github.com/luuuis/hass_omie/assets/161006/09f04768-0f93-4293-afb7-ceb491aaab61"/>

Em geral os preços PT/ES são iguais mas se aguentares até às 7 da manhã aí sim poderás observar a diferença entre o preço em PT e ES. 😄😄😄

**Comment by r-amado** [comment]
Compreendido. Agora faz mais sentido!

**Comment by luuuis** [comment]
Caso alguém venha aqui ter futuramente penso que isto está mais bem explicado em [Interpretação OMIE mercado diário](https://github.com/luuuis/hass_omie/wiki/Interpretação-OMIE-mercado-diário).
