### ISSUE TITLE
"Não foram encontradas estatísticas" no Histórico do sensor

### ISSUE THREAD

**Issue by codedmind** [luuuis/hass_omie#27]
Alterando a unidade não fará que os graficos depois já aparecem no homeassintant?
![image](https://github.com/luuuis/hass_omie/assets/2910047/49d7a2cb-1f57-4a96-a39f-7fec837f793a)

**Comment by luuuis** [comment]
Deves estar com erros nas estatísticas, verifica em https://my.home-assistant.io/redirect/developer_statistics/  e aplica as correcções necessárias.

<img width="400" src="https://github.com/luuuis/hass_omie/assets/161006/e96f8295-6017-4d26-8edc-224c86f721e6"/>

**Comment by luuuis** [comment]
@codedmind como é a 3ª vez que não o fazes, lembro que é de bom tom voltar aqui para actualizar as pessoas estão a dispor do seu tempo para resolver os problemas que reportas. Não custa nada e também ajuda os outros utilizadores a saber o que resulta e o que não resulta, caso venham a ter o mesmo problema.

Dado a ausência de confirmação parto do princípio que está resolvido.

**Comment by codedmind** [comment]
Viva,
Não cheguei a testar... ainda não voltei a conseguir olhar para isso, sorry


Luis Miranda ***@***.***> escreveu no dia quarta, 14/06/2023
à(s) 11:25:
