### ISSUE TITLE
Erro em grafico 

### ISSUE THREAD

**Issue by afonsoreis** [luuuis/hass_omie#28]
Olá, 
Desde já muito obrigado pelo projecto.

Estou com problemas ao criar o gráfico ApexChart: Today's hourly values, fico sempre com este erro:

**/// apexcharts-card version 2.0.4 /// value.all_series_config is not a ChartCardAllSeriesExternalConfig; value.all_series_config.show is not a ChartCardSeriesShowConfigExt; value.all_series_config.show.data_generator is extraneous**

já percebi que o problema está nesta linha de código: return **Object.entries(entity.attributes.today_hours).map(([dateString, price]) => [ new Date(dateString), price ]), mas não faço ideia de como resolver!** 

Obrigado

**Comment by luuuis** [comment]
@afonsoreis o espaçamento estava mal no YAML do exemplo, tenta de novo:

https://github.com/luuuis/hass_omie/wiki/ApexChartsTodayHourlyValues

**Comment by afonsoreis** [comment]
Perfeito! Muito obrigado Luis, funciona perfeitamente.

Seria muito pedir um gráfico igual mas para os valores da Luzboa? ou seja, podermos saber o preço que irá estar a eletricidade na Luzboa bi-horário durante o dia. 

Um forte abraço e obrigado pelo trabalho!

**Comment by luuuis** [comment]
Isso é pedir muito. :)

Agora a sério, o mesmo gráfico pode ser adaptado para também mostrar os preços das operadoras. No teu caso basta mudar ou acrescentar a série [`luzboa_spot_btn_bihorario`](https://github.com/luuuis/hass_omie/wiki/Luzboa-SPOT-BTN-Bi-horário) ao gráfico.

Vê também o [Yesterday/Today/Tomorrow](https://github.com/luuuis/hass_omie/wiki/ApexChartsYesterdayTodayTomorrow) que é um exemplo mais completo que mistura consumos com preços. Em particular, a série `sensor.MY_ELECTRICITY_PURCHASE_PRICE` faz o que tu pretendes.
