### ISSUE TITLE
Média do dia - cálculo errado?

### ISSUE THREAD

**Issue by JFRosado** [luuuis/hass_omie#29]
É impressão minha, ou a média do dia não está a ser bem calculada? 

Tendo em conta que o mercado negoceia os valores em Espanha com a hora de Espanha+1, a média do dia não deveria ser as 2 horas do dia anterior mais as 22 horas do dia de hoje? 

Isto para Portugal.

**Comment by luuuis** [comment]
Alô, consegues ser mais específico?
1. Qual média (há várias)?
2. Em que data ou datas? Quais os valores horários?
3. Que valor é calculado?
4. Que valor deveria ser calculado?

Ou então referência directa e explicação do código que está mal.

**Comment by JFRosado** [comment]
Estou a falar da média do dia para Portugal

Por exemplo, a média de hoje será a soma dos valores das 22h de ontem às 22h de hoje. 

Nos teus cálculos está a soma das 23h00 de ontem às 23h00 de hoje.

**Comment by luuuis** [comment]
> a média de hoje será a soma dos valores das 22h de ontem às 22h de hoje a dividir pelas 24h

O que te leva a dizer isto, 22h por que motivo? A diferença horário de momento é de 1h.

PS não sei se já leste o #25 mas existe lá alguma discussão acerca do mesmo assunto.

**Comment by JFRosado** [comment]
Digo isto, porque nos valores retornados para os preços de amanhã, por exemplo no mercado Espanhol, o ultimo valor não existe (está a null):

> today_provisional: false
```
tomorrow_average: 84.63
tomorrow_hours: 
'2023-06-18T00:00:00+01:00': 108.87
'2023-06-18T01:00:00+01:00': 103.19
'2023-06-18T02:00:00+01:00': 100
'2023-06-18T03:00:00+01:00': 96.01
'2023-06-18T04:00:00+01:00': 86.81
'2023-06-18T05:00:00+01:00': 94.75
'2023-06-18T06:00:00+01:00': 92.06
'2023-06-18T07:00:00+01:00': 85
'2023-06-18T08:00:00+01:00': 78.17
'2023-06-18T09:00:00+01:00': 63.53
'2023-06-18T10:00:00+01:00': 53.88
'2023-06-18T11:00:00+01:00': 46
'2023-06-18T12:00:00+01:00': 29.52
'2023-06-18T13:00:00+01:00': 25.1
'2023-06-18T14:00:00+01:00': 49.14
'2023-06-18T15:00:00+01:00': 55
'2023-06-18T16:00:00+01:00': 70.11
'2023-06-18T17:00:00+01:00': 80.77
'2023-06-18T18:00:00+01:00': 104
'2023-06-18T19:00:00+01:00': 125.47
'2023-06-18T20:00:00+01:00': 134.02
'2023-06-18T21:00:00+01:00': 137.06
'2023-06-18T22:00:00+01:00': 128.13
'2023-06-18T23:00:00+01:00': null
```

Por isso suponho que este valor corresponde à hora da meia-noite à 1h da manhã do dia depois de amanhã em Espanha?

**Comment by luuuis** [comment]
> nos valores retornados para os preços de amanhã, por exemplo no mercado Espanhol, o ultimo valor não existe (está a null)

@JFRosado os preços de amanhã que vês são os seguintes:
- `2023-06-18T00:00:00+01:00`: 00h de amanhã em PT == 01h de **amanhã** em ES,
- ...
- `2023-06-18T23:00:00+01:00`: 23h de amanhã em PT == 00h de **depois de amanhã** em ES.

Ora, os valores para **depois de amanhã** não serão conhecidos senão depois da conclusão do [mercado diário que vai ocorrer às 12h de amanhã]( Espanha) (horário ES). Por esta razão a média do dia PT só pode ser calculada depois das cerca de 11:30 de PT. Até lá está em falta a última hora do dia.

Existem atributos no sensor chamados `today_provisional` e `tomorrow_provisional` que te dizem se os valores estão completos ou não.

**Comment by luuuis** [comment]
Penso que a questão está esclarecida.

**Comment by luuuis** [comment]
Caso alguém venha aqui ter futuramente penso que isto está mais bem explicado em [Interpretação OMIE mercado diário](https://github.com/luuuis/hass_omie/wiki/Interpretação-OMIE-mercado-diário).
