### ISSUE TITLE
É possível criar sensor para Simples Energia?

### ISSUE THREAD

**Issue by tukestolo** [luuuis/hass_omie#30]
A formula para o mercado indexado é a seguinte:

PE(h) = (POMIE(h) – K1) x Excedente
POMIE(h)  = Preço da Energia horária no Mercado Diário OMIE-Portugal(em €/MWh)
K1 (€/MWh) = Valor fixo correspondente aos gastos operacionais da Simples
VALOR K1 = 10 € / MWh

Exemplo apenas ilustrativo:
No dia 10/05 às 12:00 o preço do mercado foi 201,50€/MWh – 0,2015€/kWh e o excedente injetado na rede para essa hora foi 10 kWh.
 
O valor a receber será: 10* (0,2015-0,010) = 1,92€

**Comment by luuuis** [comment]
@tukestolo presumo que isso seja preço de venda, certo? Qual a remuneração se o POMIE(h) for <10 como ocorreu ontem entre as 8 e as 18?

**Comment by luuuis** [comment]
@tukestolo sim, chegou a [0 €/MWh](https://www.omie.es/pt/market-results/daily/daily-market/daily-hourly-price?scope=daily&date=2023-08-27).

**Comment by luuuis** [comment]
Entretanto espreita https://github.com/luuuis/hass_omie/wiki/Energia-Simples-excedente-indexado

**Comment by tukestolo** [comment]
@luuuis faz sentido para ti? 
Foi a resposta dada por eles:

O calculo é feito de hora em hora, deixo o exemplo real de um período que faturamos.
                                Excedente(h) x (preço OMIE(h) – 10€/MWh)
2023-07-29 15H :: 0.001258 MWh x ( 83.000 €/MWh - 10 €/MWh ) = 0.091834 €
2023-07-29 16H :: 0.001837 MWh x ( 79.2200 €/MWh - 10 €/MWh ) = 0.12715714 €
2023-07-29 17H :: 0.002258 MWh x ( 72.5900 €/MWh - 10 €/MWh ) = 0.14132822 €
2023-07-29 18H :: 0.001321 MWh x ( 69.000 €/MWh - 10 €/MWh ) = 0.077939 €
2023-07-29 19H :: 0.000373 MWh x ( 73.1000 €/MWh - 10 €/MWh ) = 0.0235363 €
2023-07-29 20H :: 0 MWh x ( 83.3500 €/MWh - 10 €/MWh ) = 0 €
2023-07-29 21H :: 0 MWh x ( 100.6500 €/MWh - 10 €/MWh ) = 0 €

ou seja, nesse dia eu iria receber 0 e tambem nao ia pagar nada, certo ?

**Comment by luuuis** [comment]
Em todos esses exemplos o €/MWh é maior que 10 por isso não vai de encontro à minha dúvida. O que o sensor faz actualmente nesse caso é considerar remuneração 0.
