### ISSUE TITLE
Cálculo do preço Coopérnico em €/MWh

### ISSUE THREAD

**Issue by JFRosado** [luuuis/hass_omie#31]
Não percebo porque raio o preço nos simuladores (neste caso Coopérnico, mas nos outros é igual) são calculados em custo/MWh..

Mas eu por acaso pago ao MWh, ou ao kWh?

Já tentei corrigir as fórmulas, mas acaba sempre por não calcular os preços do dia seguinte...

Já agora as perdas não são 15%..as perdas são obtidas num ficheiro de excel na erse e são diferentes a cada 15 minutos. A média de todos os valores deste ano dá cerca de 8,5%

**Comment by luuuis** [comment]
Viva @JFRosado,

Os valores dos leilões OMIE são em €/MWh e este addon evita fazer conversões. Até há algumas vantagens em usar €/MWh, quanto a isso podes ler o que escrevi em #8 que também mostra algumas alternativas para visualizar em €/KWh, mas acaba por ser uma preferência minha.

Penso que estás a queixar-te especificamente dos templates, que em rigor não fazem parte do addon. Eu compreendo que possa ser chato não apresentarem a informação como gostarias mas a solução por enquanto é mesmo editar os templates (isto além das alternativas que apresentei no #8). Qual a dificuldade específica que tiveste em calcular em €/kWh os preços do dia seguinte? Talvez eu consiga ajudar.

PS Fiquei intrigado em relação às perdas, tens mais informação acerca disso? Nomeadamente, consegue-se consultar esses dados em tempo real? Se quiseres e puderes facultar (em novo issue) agradeço.

**Comment by JFRosado** [comment]
Olá:

     Já consegui alterar para calcular em €/kWh. Dá jeito para calcular o valor da fatura final
