### ISSUE TITLE
Atributos

### ISSUE THREAD

**Issue by rexp2** [luuuis/hass_omie#34]
Hola Luis, tenía todo bien pero con ésta versión han cambiado los atributos y ya no sé manejarlos.
Puedes decirme como puedo ver el precio de una hora en concreto sin que salga la fecha,etc.
Gracias

**Comment by luuuis** [comment]
Olá,

Qual versão? Não houve alterações recentes nos atributos.

**Comment by rexp2** [comment]
No tengo claro que versión anterior utilizaba pero era diferente y me ha dejado de funcionar al actualizar HA así que he actualizado a la última y ahora no sé como sacar el precio omie a las 12 horas, por ejemplo.
Como puedo hacer un sensor que me muestre el precio a las 12 horas?

**Comment by luuuis** [comment]
Penso que já discutimos isto anteriormente em https://github.com/luuuis/hass_omie/issues/20. :)

> Como puedo hacer un sensor que me muestre el precio a las 12 horas?

Muito simplesmente assim:
```
{{ (state_attr('sensor.omie_spot_price_es', 'today_hours').values()|list)[12] }}
```

**Comment by rexp2** [comment]
Ups!! Si que lo hablamos. 
Algo tengo mal entonces. 
Perdona por molestar.
Obrigado

**Comment by luuuis** [comment]
```
{% set omie = state_attr('sensor.omie_spot_price_es', 'today_hours').values()|list %}
```
