### ISSUE TITLE
No actualiza datos desde ayer a las 10.30

### ISSUE THREAD

**Issue by jellyfinuser** [luuuis/hass_omie#37]
Buenos dias, lo he tenido tiempo funcionando correctamente, pero desde ayer a las 10.30 (quizá sobre esa hora hice un update de home assistant core) ha dejado de fucnionar la integración , vuelvo a recargarlo, reinstalarlo, pero el ultimo dato que aparece es ayer a las 10.30. hay algun problema con la versión o similar?

**Comment by jsantosdias** [comment]
Necesitas actualizar a la nueva versión...

**Comment by luuuis** [comment]
Passo 1: instalar a [v1.0.2](https://github.com/luuuis/hass_omie/releases/tag/v1.0.2)
Passo 2: se houver problemas, fornecer mais informação aqui (versão HA, versão OMIE, descrição do erro, logs)

**Comment by jellyfinuser** [comment]
OK thanks! yesterday not appear any update, but today appeared and updated, all work, thanks a lot and sorry!

**Comment by luuuis** [comment]
Tranquilo 👍
