### ISSUE TITLE
Erro ao criar integração

### ISSUE THREAD

**Issue by vantunes** [luuuis/hass_omie#38]
Ao acresentar o custom repositoris no hacs dá um erro

Cannot connect to host api.github.com:443 ssl:default [Name has no usable address]

como na imagem

![image](https://github.com/luuuis/hass_omie/assets/2738651/bb7b5091-688a-4ff8-849d-eea9701042f9)

O que ha de errado?

**Comment by vantunes** [comment]
![image](https://github.com/luuuis/hass_omie/assets/2738651/e58264b8-593b-42af-9f9c-ccee4ebf1549)

**Comment by luuuis** [comment]
Viva, 

Não é necessário acrescentar o repositório, já vem configurado no HACS. Procede como se já tivesses completado esse passo. 

Irei corrigir as instruções, obrigado pelo alerta.

**Comment by vantunes** [comment]
Não encontro no HACS a intração do OMIE
Queria configurar para ter o preço da coopernico
