### ISSUE TITLE
OMIE - electricity market operator for the Iberian Peninsula" integration stopped working for me at 29 October 2023 at 00h.

### ISSUE THREAD

**Issue by JeffersM1** [luuuis/hass_omie#39]
Error message is:
TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.omie_spot_price_pt')|float }}' but no default was specified') while processing template 'Template<template=({{ states('sensor.omie_spot_price_pt')|float }}) renders=28>' for attribute 'PM' in entity 'sensor.coopernico_base_tarifario_tri_horario'

It seems like the "OMIE - electricity market operator for the Iberian Peninsula" integration stopped working for me at 29 October 2023 at 00h.

The OMIE service is working and pulling in values.

**Comment by JeffersM1** [comment]
On second confirmation, the integration is pulling in the values.  It is that tariff templates that are causing errors even for the Coopérnico Simples tariff.

**Comment by JeffersM1** [comment]
In the development tools template debugger I made the following change to get rid of the float error:
replaced all instances of "|float" with "|float(0)"
Now the only error is "UndefinedError: None has no element datetime.datetime(2023, 10, 29, 0, 0, tzinfo=<DstTzInfo 'Europe/Lisbon' WEST+1:00:00 DST>)"

**Comment by JeffersM1** [comment]
I went in and updated the tariff templates to replace all instances of "|float" with "|float(0)" and restarted yaml configurations.  Now the tariff sensors are working.

**Comment by zcsrf** [comment]
Hi JeffersM1,
Also had the same issue.

Where you able to fix the apex charts code? 
Didn't did any debug yet but it seems today/tomorrow charts don't work.

**Comment by nfgb** [comment]
Hi @JeffersM1,
I believe the issue is on the omie site. This url https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT
which sould have the adjustment price for today is unavailble.
I used your workarond and the sensor is working again (assuming zero for the ajustment price when it cannot get from the site), the only thing i'm missing is the attributes for today and tomorrow hours.

**Comment by JeffersM1** [comment]
I am not using Apex Charts, as I'm not quite sure on how to use them yet.  I just replaced all instances of "|float" with "|float(0)" in the tariff templates and restarted yaml configurations. Now all the price sensors are working for me.  
It was the code on these pages that were giving me problems:
https://github.com/luuuis/hass_omie/wiki/Coop%C3%A9rnico-Base-Simples
https://github.com/luuuis/hass_omie/wiki/Coop%C3%A9rnico-Base-Bi-hor%C3%A1rio
and also a template I made for Tri-Horário

**Comment by JeffersM1** [comment]
> Hi @JeffersM1, I believe the issue is on the omie site. This url https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT which sould have the adjustment price for today is unavailble. I used your workarond and the sensor is working again (assuming zero for the ajustment price when it cannot get from the site), the only thing i'm missing is the attributes for today and tomorrow hours.

Are you seeing updated values in the sensor, or just zeros?  I am getting actual values.
![image](https://github.com/luuuis/hass_omie/assets/97175692/23b5517e-c519-47a7-a2a6-7acded74c951)

The Adjustment mechanism price (MAJ or MIBEL) has never returned values for me, so I had assumed that it was not currently in use.  

The Excedentes template didn't have the issue this morning.  Instead of using "|float", it uses "|float(default=None)".

**Comment by nfgb** [comment]
> > Hi @JeffersM1, I believe the issue is on the omie site. This url https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT which sould have the adjustment price for today is unavailble. I used your workarond and the sensor is working again (assuming zero for the ajustment price when it cannot get from the site), the only thing i'm missing is the attributes for today and tomorrow hours.
> 
> Are you seeing updated values in the sensor, or just zeros? I am getting actual values. ![image](https://user-images.githubusercontent.com/97175692/278868106-23b5517e-c519-47a7-a2a6-7acded74c951.png)
> 
> The Adjustment mechanism price (MAJ or MIBEL) has never returned values for me, so I had assumed that it was not currently in use.
> 
> The Excedentes template didn't have the issue this morning. Instead of using "|float", it uses "|float(default=None)".

Now I see the same as you, maybe it took same time to populate the values for today values ( Tomorrow value are still null but should be normal).

Another thing I've noted is that the marginal price is 0.96 on the sensor but on the omie site is 0.6 for the 11th hour, 0.96 is for th 13th hour, but maybe I'me misreading the data on the omie site.

![image](https://github.com/luuuis/hass_omie/assets/6281540/7c5025d3-da0a-4377-bba5-699c5eda23d3)

**Comment by JeffersM1** [comment]
> > > Hi @JeffersM1, 
> 
> Another thing I've noted is that the marginal price is 0.96 on the sensor but on the omie site is 0.6 for the 11th hour, 0.96 is for th 13th hour, but maybe I'me misreading the data on the omie site.
> 
> ![image](https://user-images.githubusercontent.com/6281540/278868900-7c5025d3-da0a-4377-bba5-699c5eda23d3.png)

I think Luis had mentioned something like this in another issue.  It had to do with the time difference and I think something else between Portugal and Spain.  https://github.com/luuuis/hass_omie/issues/25

Has the Adjustment mechanism price (MAJ or MIBEL) has ever returned values for you?  I have never seen values from that sensor.

**Comment by nfgb** [comment]
Hi, @JeffersM1,

Regarding the attributes, I've confused myself, the sensor.omie_spot_price_pt is is showing the attibutes. The template is the one not showing the attributes. Do you have the Today/tomorrow hour attributes in the tariff template?

**Comment by JeffersM1** [comment]
Hi @nfgb , I am not getting the today and tomorrow hours either.  But I haven't been using them, although I do reference them in an Apex chart not working now).  Do you use these attributes only as a visual, or do yo incorporate them into some controls for hardware?
![image](https://github.com/luuuis/hass_omie/assets/97175692/f6a7ba98-c8f6-4460-b253-ee7936c1b157)

When I try to test any of the tariff templates in the development tools template debugger, I get the following error: 
"UndefinedError: None has no element datetime.datetime(2023, 10, 29, 0, 0, tzinfo=<DstTzInfo 'Europe/Lisbon' WEST+1:00:00 DST>)"

Maybe this is related to the missing attributes?

**Comment by JeffersM1** [comment]
@nfgb "I'm sure it returned zero instead of "Unknown" and the zero is normal since the last time the Adjustment mechanism was <> 0 was in Feb 2023"

I probably just wasn't paying attention that it was actually 0 values.  I have only been using these templates since about April 2023.

**Comment by nfgb** [comment]
> Hi @nfgb , I am not getting the today and tomorrow hours either. But I haven't been using them, although I do reference them in an Apex chart not working now). Do you use these attributes only as a visual, or do yo incorporate them into some controls for hardware? ![image](https://user-images.githubusercontent.com/97175692/278876854-f6a7ba98-c8f6-4460-b253-ee7936c1b157.png)
> 
> When I try to test any of the tariff templates in the development tools template debugger, I get the following error: "UndefinedError: None has no element datetime.datetime(2023, 10, 29, 0, 0, tzinfo=<DstTzInfo 'Europe/Lisbon' WEST+1:00:00 DST>)"
> 
> Maybe this is related to the missing attributes?

@JeffersM1  I only use the attributes visually ( they're very useful). And I think you're probably right it should be related to that error.

**Comment by jsantosdias** [comment]
I think it's ok, now... Works for me again...

**Comment by cliffdude** [comment]
I made the change float to float(0) on the templates,  re-downloaded the custom component in HACS to get the latest 1.0.2 version and everything is working again including the APEX charts. Thanks guys and Luuuis for this really useful component.

**Comment by luuuis** [comment]
From reading this thread I am not sure what the problem was. I seems that:
1. Sensor `sensor.omie_adjustment_price_pt` became unavailable on 
2. All electricity reseller sensors (Coopérnico, etc) that use the `sensor.omie_adjustment_price_pt` became unavailable because of (1). This is expected, we need the adjustment price to calculate the total cost.

![History – Home Assistant 2023-10-31 11-43-45](https://github.com/luuuis/hass_omie/assets/161006/fc5fe287-d09e-4414-84f0-eafe42531751)

@nfgb has said that [INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT](https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT) was not available for some time. That would cause (1) for sure and this points to a problem in OMIE.es rather than in the integration.

Questions that I still have:
1. When did the [INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT](https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT) file become available?
2. Once the file became available how quickly did the integration recover and start displaying values for `sensor.omie_adjustment_price_pt` again?

**Comment by JeffersM1** [comment]
I saw that the Apex charts were working sometime early Monday morning.  Aside from this integration, how many other users would have been affected by the unavailability of the [INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT](https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_MAJ_EV_H_29_10_2023_29_10_2023.TXT) file?
