### ISSUE TITLE
Preços em Tabela

### ISSUE THREAD

**Issue by manuelmrmorgado** [luuuis/hass_omie#40]
Boa noite,

Seria possível a representação dos dados em tabela como neste projecto? 
https://github.com/lozzd/octopus-energy-rates-card

Obrigado!!

**Comment by luuuis** [comment]
Viva,

O hass_omie é uma integração de "backend" e como tal não vai conter cards para os dashboards mas somente puxar a informação para dentro do HA. Permite sim que outras integrações de UI peguem na informação e apresentem como melhor entenderem, tal como o https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy possibilita esse card que encontraste.

Se alguém quiser a criar essa integração de UI, ou mesmo a modificar a octopus-energy-rates-card para que funcione, estou disponível para ajudar/orientar.
