### ISSUE TITLE
desfasamento horário ?

### ISSUE THREAD

**Issue by gonmag8** [luuuis/hass_omie#43]
Bom dia.
Antes de mais obrigado pelo excelente trabalho.
Perdoem-me se a pergunta for parva visto que sou newbie nestas andanças .

Ultimamente parece me que o preço que me aparece no Home assistant anda desfasado do preço do site da OMIE.es por 2 horas.

Escrevo isto pelas 10:20 da manha, o preço no Home Assistant esta a dar 25/MWh e no site da OMIE o preço das 10 é 44/MWh.
No site da OMIE o preço só irá ser 25 ao meio dia.
Nao sei se temos de aplicar a diferença horaria no site da OMIE, mas mesmo que assim seja o preço devia ser 40.1 e não 25. ?
O que me está a falhar ?

Obrigado
Gonçalo Manuel

**Comment by luuuis** [comment]
Está tudo explicado aqui: https://github.com/luuuis/hass_omie/wiki/Interpretação-OMIE-mercado-diário
