### ISSUE TITLE
Tomorrows rates not displaying correctly

### ISSUE THREAD

**Issue by JeffersM1** [luuuis/hass_omie#45]
Esta manhã, actualizei as TAR de amanhã de acordo com as novas taxas que começam em 1 de janeiro de 2024:
```
      tomorrow_hours: >
       {% set CGS = 4.0 -%}
       {%- set k = 10.0 -%}
       {%- set FP = 0.15 -%}
       {%- set TAR_vazio = 9.2 -%}
       {%- set TAR_ponta = 151.1 -%}
       {%- set TAR_cheias = 23.7 -%}
```
```
      today_hours: >
       {% set CGS = 4.0 -%}
       {%- set k = 10.0 -%}
       {%- set FP = 0.15 -%}
       {%- set TAR_vazio = -34.9 -%}
       {%- set TAR_ponta = 81.8 -%}
       {%- set TAR_cheias = -23.2 -%}
```
Mas o que estou a ver no gráfico da Apex não me parece correto para amanhã.  As taxas de pico parecem demasiado baixas.  Mais alguém está a ver algo semelhante?
![image](https://github.com/luuuis/hass_omie/assets/97175692/5d081c4b-f09a-4c79-b487-7ab0207b964b)

**Comment by luuuis** [comment]
Alô, penso que és capaz de ser o único em tri-horário mas se as alterações aos valores foram feitas correctamente então se estava correcto antes continua correcto agora.

**Comment by JeffersM1** [comment]
Pode publicar uma fotografia do que tem para os preços de amanhã com as TAR?  Pode ser de duas em duas horas ou simples, pois o conceito é o mesmo.

**Comment by JeffersM1** [comment]
Isto é o que recebo para as tarifas bi-horárias de amanhã com as novas TARs.
![image](https://github.com/luuuis/hass_omie/assets/97175692/781273d1-c01e-4c45-aa5f-d8b1687b8ae7)

Este é o meu código:
```
- name: "Coopérnico Base (tarifário bi-horário)"
  unique_id: coopernico_spot_price_bihorario
  unit_of_measurement: "€/MWh"
  state_class: measurement
  state: >
    {% set PM = states('sensor.omie_spot_price_pt')|float(0) -%}
    {% set MAJ = states('sensor.omie_adjustment_price_pt')|float(0) -%}
    {% set CGS = 4 -%}
    {% set k = 10 -%}
    {% set FP = 0.15 -%}
    {% set TAR_vazio = -34.9 -%}
    {% set TAR_fora_vazio = -0.5 -%}
    {% set TAR = TAR_vazio if now().hour < 8 or now().hour > 21 else TAR_fora_vazio -%}

    {{ ((PM + CGS + k)*(1 + FP) + MAJ + TAR) | round(2) }}
  attributes:
    friendly_name: "Coopérnico Base (tarifário bi-horário)"
    formula: "(PM+CGS+K)*(1+FP)+MIBEL+TAR"
    PM: "{{ states('sensor.omie_spot_price_pt')|float(0) }}"
    MIBEL: "{{ states('sensor.omie_adjustment_price_pt')|float(0) }}"
    CGS: "{{ 4 | float(0) }}"
    k: "{{ 10 | float(0) }}"
    FP: "{{ 0.15 | float(0)  }}"
    TAR_vazio: "{{ -34.9 | float(0) }}"
    TAR_fora_vazio: "{{ -0.5 | float(0) }}"
    TAR: "{{ TAR | float(0) }}"
    today_hours: >
      {% set CGS = 4 -%}
      {% set k = 10 -%}
      {% set FP = 0.15 -%}
      {% set TAR_vazio = -34.9 -%}
      {% set TAR_fora_vazio = -0.5 -%}

      {% set ns = namespace(hourly_data=[]) %}
      {% for h, PM in state_attr('sensor.omie_spot_price_pt', 'today_hours').items() -%}
      {% set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'today_hours')[h] -%}
      {% set TAR = TAR_vazio if h.hour < 8 or h.hour > 21 else TAR_fora_vazio -%}

      {% if PM == None or MAJ == None %}
         {% set price=PM %}
        {% else %}
         {% set price=((PM + CGS + k)*(1 + FP) + MAJ + TAR) | round(2) %}
      {% endif %}
      {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %}
      {% endfor -%}
      {{ dict(ns.hourly_data) }}
    tomorrow_hours: >
      {% set CGS = 4 -%}
      {% set k = 10 -%}
      {% set FP = 0.15 -%}
      {% set TAR_vazio = 9.2 -%}
      {% set TAR_fora_vazio = 50.2 -%}

      {% set ns = namespace(hourly_data=[]) %}
      {% for h, PM in state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours').items() -%}
        {% set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'tomorrow_hours')[h] -%}
        {% set TAR = TAR_vazio if h.hour < 8 or h.hour > 21 else TAR_fora_vazio -%}

        {% if PM == None or MAJ == None %}
          {% set price=PM %}
        {% else %}
          {% set price=((PM + CGS + k)*(1 + FP) + MAJ + TAR) | round(2) %}
        {% endif %}
        {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %}
      {% endfor -%}
      {{ dict(ns.hourly_data) }}
```

**Comment by JeffersM1** [comment]
Se eu colocar as novas taxas no gráfico Apex dos preços de hoje, parece normal.  Espero que o gráfico de amanhã se resolva quando for publicado amanhã à tarde.

![image](https://github.com/luuuis/hass_omie/assets/97175692/d471d8b6-0518-4f15-8924-ea328c2c4f32)

**Comment by luuuis** [comment]
@JeffersM1 revê cuidadosamente as alterações que fiz para o Coopérnico bi-horário e replica do teu lado. Atenção que o `tomorrow_hours` tem um tratamento ligeiramente diferente pois tem de aplicar as TAR de amanhã, hoje (corrigi essa lacuna há minutos).

https://github.com/luuuis/hass_omie/wiki/Coop%C3%A9rnico-Base-Bi-hor%C3%A1rio/_compare/0c47a17727ca5aa990d5fb6f58b04bfec75bff70...ca6f59556567dcfc83aa325e7842a9a7c92f1567?diff=unified&w=

Não vou dar suporte a configurações de Apex Charts pois nada mudou aí, é deixar tudo como estava anteriormente e verificar os sensores directamente. Localmente tenho estes valores para Coopérnico Base Bi-horário (valores já incluem IVA a 23%).

![Home – Home Assistant 2023-12-31 17-54-59](https://github.com/luuuis/hass_omie/assets/161006/4c035c0e-d81c-47d3-9b1f-db9534f3b828)

**Comment by JeffersM1** [comment]
Parece que o meu problema estava aqui: nas horas de amanhã eu tinha:
```
{%- set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'tomorrow_hours')[h]  -%}
```
Em vez de:
```
{%- set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'tomorrow_hours')[h] | float(0) -%}
```

**Comment by JeffersM1** [comment]
Isto é o que tenho agora para amanhã:
![image](https://github.com/luuuis/hass_omie/assets/97175692/fe5f40c1-9b1a-4f97-a414-f4e3893fe4ae)

Obrigado pela vossa ajuda.

**Comment by JeffersM1** [comment]
Agora está a funcionar bem.  Obrigado por acrescentar o código que permite introduzir as novas TAR com bastante antecedência, de modo a que só entrem em vigor automaticamente quando ocorrer a data de passagem para o euro.
