### ISSUE TITLE
Sítio omie não está a fornecer as tarifas

### ISSUE THREAD

**Issue by JeffersM1** [luuuis/hass_omie#48]
O sítio omie não está a fornecer as tarifas para amanhã?

![image](https://github.com/luuuis/hass_omie/assets/97175692/1df14492-c5f2-4b57-88cb-3526592e5fbd)

**Comment by JeffersM1** [comment]
O sensor de integração sensor.omie_spot_price_pt tem os preços de amanhã.  Deve haver algo de errado no meu modelo de tarifário.

**Comment by joaocbatista** [comment]
![image](https://github.com/luuuis/hass_omie/assets/100242707/9a3cd596-3ee8-47e3-8ef0-fff860aae347)

o meu sensor não tem os preços de amanhã. E por conseguinte, também não tenho os valores para o template LuzBoa que uso... deve haver algum problema com a API do site OMIE?

**Comment by JeffersM1** [comment]
Parece que o problema está no MAJ.  O modelo testa se é igual a "unknown", e, se for, é utilizado um valor de zero, mas parece que o teste falha, mas MAJ é não-numérico.

Alterei a linha no cálculo da tarifa de amanhã de:
```
{%- set price = ((PM + CGS + k)*(1.0 + FP) + MAJ + TAR) | round(2) %}
```
para
```
{%- set price = ((PM + CGS + k)*(1.0 + FP) + 0 + TAR) | round(2) %}
```

Agora está a funcionar para mim.

**Comment by JeffersM1** [comment]
Talvez seja melhor efetuar esta alteração tanto no cálculo da tarifa de hoje como no de amanhã.  Penso que o MAJ já não está a ser fornecido.

**Comment by joaocbatista** [comment]
entretanto forcei um reboot do HA e já foi fazer fetch...

**Comment by JeffersM1** [comment]
> However, I forced a reboot of the HA and it was already fetching...

Por isso, talvez tenha sido apenas o facto de ter recarregado o yaml depois de ter feito a alteração ao modelo e não a alteração do código.  É estranho que ambos tenhamos visto o problema ao mesmo tempo e que só tenhamos feito os cálculos da tarifa de amanhã.

**Comment by JeffersM1** [comment]
> entretanto forcei um reboot do HA e já foi fazer fetch...

Por isso, talvez tenha sido apenas o facto de ter recarregado o yaml depois de ter feito a alteração ao modelo e não a alteração do código.  É estranho que ambos tenhamos visto o problema ao mesmo tempo e que só tenhamos feito os cálculos da tarifa de amanhã.

**Comment by JeffersM1** [comment]
Agora está a funcionar devido à definição de MAJ para 0 ou ao reinício do yaml.

**Comment by JeffersM1** [comment]
> Futuramente seria bom capturar os logs correspondentes a estes eventos para poder corrigir um eventual problema na integração.

Os registos mostram estes dois erros:
This error originated from a custom integration.

Logger: custom_components.omie.coordinator
Source: helpers/update_coordinator.py:306
Integration: OMIE - electricity market operator for the Iberian Peninsula (documentation, issues)
First occurred: 2:00:12 PM (4 occurrences)
Last logged: 4:00:12 PM

Timeout fetching omie.adjustment_next data
Timeout fetching omie.spot_next data
Timeout fetching omie.adjustment data


Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:194
Integration: Template (documentation, issues)
First occurred: February 2, 2024 at 4:30:17 PM (27 occurrences)
Last logged: 4:31:23 PM

TemplateError('UndefinedError: None has no element datetime.datetime(2024, 2, 4, 0, 0, tzinfo=<DstTzInfo 'Europe/Lisbon' WET0:00:00 STD>)') while processing template 'Template<template=({% set CGS = 4 -%} {% set k = 10 -%} {% set FP = 0.15 -%} {% set TAR = -12.1 -%} {% set ns = namespace(hourly_data=[]) %} {% for h, PM in state_attr('sensor.omie_spot_price_pt', 'today_hours').items() -%} {% set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'today_hours')[h] -%} {% if PM == None or MAJ == None %} {% set price=PM %} {% else %} {% set price=((PM + CGS + k)*(1 + FP) + MAJ + TAR) | round(2) %} {% endif %} {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %} {% endfor -%} {{ dict(ns.hourly_data) }}) renders=4>' for attribute 'today_hours' in entity 'sensor.coopernico_base_tarifario_simples'
TemplateError('UndefinedError: None has no element datetime.datetime(2024, 2, 5, 0, 0, tzinfo=<DstTzInfo 'Europe/Lisbon' WET0:00:00 STD>)') while processing template 'Template<template=({% set CGS = 4 -%} {% set k = 10 -%} {% set FP = 0.15 -%} {% set TAR = 36.5 -%} {% set ns = namespace(hourly_data=[]) %} {% for h, PM in state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours').items() -%} {% set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'tomorrow_hours')[h] -%} {% if PM == None or MAJ == None %} {% set price=PM %} {% else %} {% set price=((PM + CGS + k)*(1 + FP) + MAJ + TAR) | round(2) %} {% endif %} {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %} {% endfor -%} {{ dict(ns.hourly_data) }}) renders=4>' for attribute 'tomorrow_hours' in entity 'sensor.coopernico_base_tarifario_simples'
TemplateError('UndefinedError: 'TAR' is undefined') while processing template 'Template<template=({{ TAR | float(0) }}) renders=4>' for attribute 'TAR' in entity 'sensor.coopernico_bihorario_spot_consumption_price'
TemplateError('UndefinedError: None has no element datetime.datetime(2024, 2, 5, 0, 0, tzinfo=<DstTzInfo 'Europe/Lisbon' WET0:00:00 STD>)') while processing template 'Template<template=({% set CGS = 4 -%} {% set k = 10 -%} {% set FP = 0.15 -%} {% set TAR_vazio = 9.2 -%} {% set TAR_fora_vazio = 50.2 -%} {% set ns = namespace(hourly_data=[]) %} {% for h, PM in state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours').items() -%} {% set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'tomorrow_hours')[h] -%} {% set TAR = TAR_vazio if h.hour < 8 or h.hour > 21 else TAR_fora_vazio -%} {% if PM == None or MAJ == None %} {% set price=PM %} {% else %} {% set price=((PM + CGS + k)*(1 + FP) + MAJ + TAR) | round(2) %} {% endif %} {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %} {% endfor -%} {{ dict(ns.hourly_data) }}) renders=4>' for attribute 'tomorrow_hours' in entity 'sensor.coopernico_bihorario_spot_consumption_price'
TemplateError('UndefinedError: 'TAR' is undefined') while processing template 'Template<template=({{ TAR | float }}) renders=4>' for attribute 'TAR' in entity 'sensor.coopernico_base_tarifario_tri_horario'

**Comment by luuuis** [comment]
Só esta parte diz respeito à integração, o resto é nos templates.

```
Logger: custom_components.omie.coordinator
Source: helpers/update_coordinator.py:306
Integration: OMIE - electricity market operator for the Iberian Peninsula (documentation, issues)
First occurred: 2:00:12 PM (4 occurrences)
Last logged: 4:00:12 PM

Timeout fetching omie.adjustment_next data
Timeout fetching omie.spot_next data
Timeout fetching omie.adjustment data
```

Um erro qualquer transiente no OMIE. Tenho de pôr isto a tentar de novo quando falha à primeira...
