### ISSUE TITLE
Error setting up entry OMIE for sensor (HA 2024.3.0)

### ISSUE THREAD

**Issue by JeffersM1** [luuuis/hass_omie#49]
Após a atualização para o HA 2024.3.0, o sensor sensor.omie_spot_price_pt deixou de ser atualizado.

O registo de erros tem o seguinte:
Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 1:41:29 AM (1 occurrences)
Last logged: 1:41:29 AM

Error setting up entry OMIE for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 139, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

![image](https://github.com/luuuis/hass_omie/assets/97175692/a06c2042-d04c-422d-af6a-5eb1cc1167e6)

**Comment by JeffersM1** [comment]
Após um segundo reinício completo do HA, o sensor OMIE está agora a ser atualizado.

**Comment by JeffersM1** [comment]
Misteriosamente, o sensor começou a atualizar-se novamente.  Será que é por ter desativado a integração "Spain electricity hourly pricing (PVPC)"?

**Comment by JeffersM1** [comment]
Pensei que o sensor de preços estava a ser atualizado, mas não está.  O que devo verificar?  

Tenho isto no ficheiro de registo do sensor OMIE:
Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 8:18:31 AM (1 occurrences)
Last logged: 8:18:31 AM

Error setting up entry OMIE for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 139, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!



![image](https://github.com/luuuis/hass_omie/assets/97175692/21481db7-5b13-469b-aa6f-9c67d7587086)

**Comment by jsantosdias** [comment]
Também acontece comigo:
Não está a atualizar as horas de amanhã...


________________________________
De: JeffersM1 ***@***.***>
Enviado: 7 de março de 2024 14:37
Para: luuuis/hass_omie ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [luuuis/hass_omie] Error setting up entry OMIE for sensor (Issue #49)


Pensei que o sensor de preços estava a ser atualizado, mas não está. O que devo verificar?

Tenho isto no ficheiro de registo do sensor OMIE:
Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 8:18:31 AM (1 occurrences)
Last logged: 8:18:31 AM

Error setting up entry OMIE for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/init.py", line 139, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

image.png (view on web)<https://github.com/luuuis/hass_omie/assets/97175692/21481db7-5b13-469b-aa6f-9c67d7587086>

**Comment by luuuis** [comment]
Podem tentar a https://github.com/luuuis/hass_omie/releases/tag/v1.0.4. Não tenho, para já, a certeza que resolva o problema mas vale a pena tentar.

**Comment by JeffersM1** [comment]
@luuuis Acabei de instalar a atualização.  Até agora parece estar a funcionar, mas terei uma ideia melhor quando o Ponta TAR começar às 18h.  Depois digo-vos.

Noutro contexto, tenho alguma ideia de onde posso procurar um modelo que possa pesquisar os atributos de preço para um bloco de horas em que o preço é baixo.  Por exemplo, encontrar um bloco de 3 horas que tenha o preço mais baixo do dia e devolver esses preços.

**Comment by JeffersM1** [comment]
Às 18h 17, o preço do sensor que é apresentado é de 5,48 €/MWh de há uma hora atrás.  O preço atual deveria ser de 24,67 euros/MWh.  Mais alguém está a passar por isto?  Vejo este erro mais ou menos na altura em que o sensor deveria ser atualizado.  Poderá estar relacionado com isto?
Logger: homeassistant
Source: core.py:727
First occurred: 6:00:01 PM (6 occurrences)
Last logged: 6:00:02 PM

Error doing job: Exception in callback _TrackPointUTCTime._run_action()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1468, in _run_action
    self.hass.async_run_hass_job(self.job, self.utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 727, in async_run_hass_job
    hassjob.target(*args)
TypeError: DataUpdateCoordinator.__wrap_handle_refresh_interval() takes 1 positional argument but 2 were given

![image](https://github.com/luuuis/hass_omie/assets/97175692/5f6d0dbb-e9a1-4f75-8456-6a97a50212f8)

**Comment by joaodsantos** [comment]
Confirmo o mesmo erro, preço não actualiza, não encontro nenhum erro nos Logs.
Não sei se ajuda, e ainda não vi ninguém a comentar esta parte, a única maneira de actualizar o valor é reiniciando o Home Assistant, o restart actualiza o valor mas a partir daí deixa de actualizar

**Comment by JeffersM1** [comment]
> Confirmo o mesmo erro, preço não actualiza, não encontro nenhum erro nos Logs. Não sei se ajuda, e ainda não vi ninguém a comentar esta parte, a única maneira de actualizar o valor é reiniciando o Home Assistant, o restart actualiza o valor mas a partir daí deixa de actualizar

Sim, era isso que eu estava a ver.  Quando reiniciava o HA, via o novo preço e pensava que estava a funcionar, mas algumas horas depois ainda tinha o preço antigo.

**Comment by luuuis** [comment]
Por favor partilhem os Debug Logs.

Por aqui tudo a funcionar no 2024.1.6. Para ter isto a funcionar existem as seguintes opções:
1. Voltar à versão do HA que corriam anteriormente
1. Agendar a integração para reiniciar a cada hora através do [`homeassistant.reload_config_entry`](https://my.home-assistant.io/redirect/developer_call_service/?service=homeassistant.reload_config_entry)
2. Esperar uma nova versão (não será imediato pois há que garantir que funciona em versões recentes e mais antigas também).

**Comment by JeffersM1** [comment]
A adição da automatização para chamar o serviço parece funcionar na perfeição.

**Comment by joaocbatista** [comment]
tinha tudo a funcionar bem, e também comecei a não ter actualizações desde ontem... 

vou explorar a opção de reiniciar a integração regularmente a ver se resolve...

**Comment by JeffersM1** [comment]
Esta automatização funcionou para mim para recarregar a integração do sensor de preços:
```
alias: OMIE Portugal Spot Price Reload
description: ""
trigger:
  - platform: time_pattern
    hours: "1"
  - platform: time
    at: "12:30:05"
condition: []
action:
  - service: homeassistant.reload_config_entry
    metadata: {}
    data: {}
    target:
      entity_id: sensor.omie_spot_price_pt
mode: single

```

**Comment by jandrade66** [comment]
Bom dia,
acabei de instalar esta integração e não consigo atualuzar os sensores. A versão do HA é a 2024.3 e quando executo o reload_config_entry obtenho ester erro no log:
`Logger: homeassistant.components.sensor
Origem: helpers/entity_platform.py:350
integração: Sensor (documentação, problemas)
Primeira ocorrência: 10:02:44 (3 ocorrências)
Último registo: 10:30:28

Error while setting up omie platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omie/coordinator.py", line 87, in _async_update_data
    return await super()._async_update_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 274, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omie/coordinator.py", line 193, in fetch
    return await fetch_to_dict(client_session, source, dc.date, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omie/coordinator.py", line 131, in fetch_to_dict
    async with await session.get(source, timeout=DEFAULT_TIMEOUT.total_seconds()) as resp:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/omie/sensor.py", line 120, in async_setup_entry
    await c.today.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady
`

**Comment by dggithub1234** [comment]
[Debug_log_0000-0200_OMIE.txt](https://github.com/luuuis/hass_omie/files/14556365/Debug_log_0000-0200_OMIE.txt)
Viva,
Segue ficheiro debug log da minha instalação. 
Integração OMIE e HA com as últimas atualizações.
No ínicio de cada hora , no minuto 0, occorem um conjunto de erros que penso serem a tentativa de atualização automática da integração.
Seguem erros também da atualização de sensores template que usam dados dos sensores OMIE.
No ínicio de cada hora  no minuto 1 tenho automatizado o reload da entidade sensor.omie_spot_price_pt' que consegue atualizar com sucesso os dados.
A sequência repete-se todas as horas. 
No log coloquei apenas da 00:00-02:01

**Comment by luuuis** [comment]
Viva,

Lancei a https://github.com/luuuis/hass_omie/releases/tag/v1.0.5 que já deverá funcionar bem no 2024.3.0 (foi introduzida uma incompatibilidade nessa versão). Confirmem, por favor.

@jandrade66 o teu problema não é o que está a ser discutido aqui: o teu Wibeee não respondeu, deve precisar de um pontapé (reiniciar).

**Comment by joaodsantos** [comment]
Posso confirmar que já funciona. Desliguei a automation e actualizei o componente, os preços ja actualizam hora a hora e ja tenho os valores de amanhã, algo que também não estava a acontecer.
Obrigado pela ajuda Luis
