### ISSUE TITLE
Dúvida kWh

### ISSUE THREAD

**Issue by FilipeOS** [luuuis/hass_omie#55]
Antes de mais obrigado pelo trabalho que foi feito.

Tendo a energia simples e ibelectra bi-horario ambos indexados, se colocar /1000 obtenho em kWh e não MHw.
Fazendo isso consigo usar no separador Energy para ir buscar esses valores automaticamente certo?

Tenho dúvida porque está-me a dar 0,0020 na energia simples e 0,0997 na ibelectra.. acho o valor baixo demais na energia simples a vender? ou eles fazem a media diária/ mes?

Na ibelectra é media dos ultimos 30 dias ou mensal?

Obrigado!

**Comment by luuuis** [comment]
Olá,

Os sensores dos [Tarifários Portugal](https://github.com/luuuis/hass_omie/wiki/Tarif%C3%A1rios-Portugal) podem ser usados directamente no Energy do HA, não é necessário fazer conversões nenhumas.
![Settings – Home Assistant 2024-03-19 15-56-40](https://github.com/luuuis/hass_omie/assets/161006/b820b582-4db2-4a26-979c-3f8fb9b6f8fa)

Relativamente aos tarifários, até notícia em contrário estão actualizados. Eu não sigo todos os tarifários do mercado mas conto com as contribuições dos utilizadores neste [tópico do CPHA.pt](https://forum.cpha.pt/t/integracao-omie-precos-horarios-diarios-mecanismo-de-ajuste/11668) ou aqui no GitHub quando há alguma actualização a fazer.

**Comment by FilipeOS** [comment]
Se eu colocar assim o energy deixa de reportar dados..

Tive de fazer estes 2 sensores:

```
      - name: "Ibelectra Current Hour Price"
        unit_of_measurement: '€/kWh'
        state_class: measurement
        device_class: monetary
        state: >
          {% set current_hour = now().strftime('%Y-%m-%dT%H:00:00+00:00') %}
          {% set today_hours = state_attr('sensor.template_ibelectra_familia_bihorario', 'today_hours') %}
          {% set current_price_mwh = today_hours.get(current_hour) %}
          {% if current_price_mwh is not none %}
            {{ (current_price_mwh / 1000) | round(4) }}
          {% else %}
            0
          {% endif %}

      - name: "Energia Simples Current Hour Price"
        unit_of_measurement: '€/kWh'
        state_class: measurement
        device_class: monetary
        state: >
          {% set current_hour = now().strftime('%Y-%m-%dT%H:00:00+00:00') %}
          {% set today_hours = state_attr('sensor.template_energia_simples_excedente_indexado', 'today_hours') %}
          {% set current_price_mwh = today_hours.get(current_hour) %}
          {% if current_price_mwh is not none %}
            {{ (current_price_mwh / 1000) | round(4) }}
          {% else %}
            0
          {% endif %}
```

**Comment by luuuis** [comment]
Não é necessário, deve haver por aí algum outro problema qualquer que pode estar a causar isso. Há erros nas estatísticas dos sensores dos tarifários?

https://my.home-assistant.io/redirect/developer_statistics/
