### ISSUE TITLE
Problema com o acesso aos dados do OMIE spot do dia seguinte

### ISSUE THREAD

**Issue by JeffersM1** [luuuis/hass_omie#61]
A minha instalação HA recebeu esta mensagem.  Há algum problema com o acesso aos dados do OMIE spot do dia seguinte? 
```
This error originated from a custom integration.

Logger: custom_components.omie.coordinator
Source: helpers/update_coordinator.py:328
integration: OMIE - electricity market operator for the Iberian Peninsula (documentation, issues)
First occurred: 12:30:01 PM (1 occurrences)
Last logged: 12:30:01 PM

Error requesting omie.spot_next data: Cannot connect to host www.omie.es:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
```
![image](https://github.com/luuuis/hass_omie/assets/97175692/ffa2c8d6-4f7a-4252-aa85-c1f706793a26)

**Comment by frankesousa** [comment]
No meu caso, com o HA versão 2024.3.2 não há problema nenhum e o omie tem os valores de hoje e amanhã

Noutro HA com a versão 2024.4.3 deixou de apresentar o preço para amanhã, entretanto tentei reiniciar a integração e o HA e agora não apresenta nenhuma informação, nem atual, nem de hoje nem amanhã.

O erro apresentado é o mesmo: 
`aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.omie.es:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]`

**Comment by JeffersM1** [comment]
Desde a semana passada, tenho o HA com a versão 2024.4.3, mas o problema só começou hoje.  Infelizmente, pouco depois de publicar este problema, reiniciei a integração e agora também não recebo os preços à vista de hoje.

**Comment by frankesousa** [comment]
> Desde a semana passada, tenho o HA com a versão 2024.4.3, mas o problema só começou hoje. Infelizmente, pouco depois de publicar este problema, reiniciei a integração e agora também não recebo os preços à vista de hoje.

Estranho, a minha instalação com 2024.3.2, agora mesmo, está a funcionar bem, e mesmo depois de reiniciar o HA não deixa de funcionar. Parece-me de algum modo relacionado com a nova versão do HA.

**Comment by abacao** [comment]
Tentei remover, reboot, adicionar e permanece sem dados.

![image](https://github.com/luuuis/hass_omie/assets/17479246/510d8db1-fc6f-460e-9861-9bf7b0a6aba5)

erro nos logs

```
Logger: homeassistant.helpers.event
Source: helpers/template.py:588
First occurred: 16:22:26 (16 occurrences)
Last logged: 16:22:26

Error while processing template: Template<template=({% set CG = 0.20 -%} {% set PM = state_attr('sensor.omie_spot_price_pt', 'tomorrow_average') -%} {% set ns = namespace(hourly_data=[]) %} {% for h, _ in state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours').items() -%} {% if PM == None or MAJ == None %} {% set price=PM %} {% else %} {% set price=(PM*(1-CG)) | round(2) %} {% endif %} {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %} {% endfor -%} {{ dict(ns.hourly_data) }}) renders=2>
Error while processing template: Template<template=({% set K1 = 10 -%} {% set POMIEh = states('sensor.omie_spot_price_pt')|float -%} {{ [POMIEh - K1, 0] | max | round(2) }}) renders=2>
Error while processing template: Template<template=({{ state('sensor.omie_spot_price_pt') }}) renders=2>
Error while processing template: Template<template=({% set K1 = 10 -%} {% set ns = namespace(hourly_data=[]) %} {% for h, POMIEh in state_attr('sensor.omie_spot_price_pt', 'today_hours').items() -%} {% if POMIEh == None %} {% set price=POMIEh %} {% else %} {% set price=[(POMIEh - K1), 0] | max | round(2) %} {% endif %} {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %} {% endfor -%} {{ dict(ns.hourly_data) }}) renders=2>
Error while processing template: Template<template=({% set K1 = 10 -%} {% set ns = namespace(hourly_data=[]) %} {% for h, POMIEh in state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours').items() -%} {% if POMIEh == None %} {% set price=POMIEh %} {% else %} {% set price=[(POMIEh - K1), 0] | max | round(2) %} {% endif %} {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %} {% endfor -%} {{ dict(ns.hourly_data) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 586, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2545, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2237, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1849, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'None' when rendering template '{{ (state_attr('sensor.omie_spot_price_pt','today_average') | int /1000) | round (2) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 712, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 588, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'None' when rendering template '{{ (state_attr('sensor.omie_spot_price_pt','today_average') | int /1000) | round (2) }}' but no default was specified
```

**Comment by filipecaldeira** [comment]
Também já tentei reboot, verificar ligação, etc... e aqui deixou mesmo de funcionar  e dá o erro que apresentam nos primeiros posts:
Core 2024.4.3
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2

**Comment by joaocbatista** [comment]
deve ter havido alguma alteração no que toca a ssl verification.

client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.omie.es:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

**Comment by frankesousa** [comment]
Pela minha ultima análise parece-me que estará relacionado com a HA OS, fiz restore do HA para a versão anterior e continua sem funcionar, mas o OS ficou na mesma o 12.2.

Numa outra instalação com o OS 12.1 está a funcionar normalmente.

**Comment by joaocbatista** [comment]
o Luis acabou de fazer release de uma versão temporária que faz disable ao ssl verify, confirmo que já funciona.

**Comment by Gusimelo** [comment]
> Pela minha ultima análise parece-me que estará relacionado com a HA OS, fiz restore do HA para a versão anterior e continua sem funcionar, mas o OS ficou na mesma o 12.2.
> 
> Numa outra instalação com o OS 12.1 está a funcionar normalmente.

Fiz downgrade da 12.2 para 12.1 e continua a não funcionar.

Já agora, a integração scrape para o omie.es também deixou de funcionar, mas se desligar a verificação de ssl já funciona.

**Comment by luuuis** [comment]
Estive a investigar e o problema deriva da forma como o omie.es está a reportar os certificados HTTPS, não tem a ver com versões de HA, HA OS ou desta integração. Pode acontecer mais ou menos esporadicamente dependendo da forma como o omie.es responde a cada pedido (pode haver certificados diferentes em uso, cada pedido é um caso).

Infelizmente tive de desactivar a validação HTTPS para desbloquear a integração até perceber se há alguma solução melhor.

https://github.com/luuuis/hass_omie/releases/tag/v1.0.9

**Comment by Gusimelo** [comment]
> Estive a investigar e o problema deriva da forma como o omie.es está a reportar os certificados HTTPS, não tem a ver com versões de HA, HA OS ou desta integração. Pode acontecer mais ou menos esporadicamente dependendo da forma como o omie.es responde a cada pedido (pode haver certificados diferentes em uso, cada pedido é um caso).
> 
> Infelizmente tive de desactivar a validação HTTPS para desbloquear a integração até perceber se há alguma solução melhor.
> 
> https://github.com/luuuis/hass_omie/releases/tag/v1.0.9

Coincidência ou não, o addon nginx proxy manager começou a falhar ao renovar os certificados let's encrypt que tinha. o HTTP-01 challenge não funciona, tive de configurar um novo certificado usando o DNS-01 challenge.

**Comment by luuuis** [comment]
O OMIE.es não está a enviar a cadeia completa de certificados necessária para a verificação, daí a falha na verificação.

![Personal — SSL Server Test: www omie es (Powered by Qualys SSL Labs) 2024-04-17 14-01-24](https://github.com/luuuis/hass_omie/assets/161006/0d78ec5e-e59b-4348-919f-b526012b0681)
https://www.ssllabs.com/ssltest/analyze.html?d=www.omie.es

Abri uma ocorrência no suporte técnico do OMIE e eles dizem que vão analisar. Entretanto vou manter este ticket aberto.

**Comment by jpedrofigueiredo** [comment]
Deparei-me com este problema hoje e após algum debug cheguei à conclusão que o pacote `ca-certificates` não inclui o certificado intermédio `GlobalSign GCC R3 DV TLS CA 2020` e que o servidor do OMIE não o está a devolver.

No meu caso, não é só o HA que está a dar erro com pedidos para `https://www.omie.es`, o curl também se queixa:
```
$ curl -I https://www.omie.es
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

A solução que pareceu mais óbvia foi fazer o download do certificado intermédio em falta `GlobalSign GCC R3 DV TLS CA 2020` e instalá-lo na "TrustStore" do sistema e do Python.
O certificado intermédio pode ser obtido facilmente, abrindo a página OMIE no browser (Chrome por exemplo), e depois:
* clicar no ícone à esquerda do URL
* seleccionar "Connection is secure"
* seleccionar "Certificate is valid"
* seleccionar tab "Details" em cima
* escolher o "Global GCC R3 DV TLS CA 2020" na caixa de cima, chamada "Certificate Hierarchy"
* clicar no botão "Export" e guardar o ficheiro com extensão `.crt`

Para quem confiar e não quiser ter trabalho, o certificado é este:
```
-----BEGIN CERTIFICATE-----
MIIEsDCCA5igAwIBAgIQd70OB0LV2enQSdd00CpvmjANBgkqhkiG9w0BAQsFADBM
MSAwHgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMzETMBEGA1UEChMKR2xv
YmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjAeFw0yMDA3MjgwMDAwMDBaFw0y
OTAzMTgwMDAwMDBaMFMxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWdu
IG52LXNhMSkwJwYDVQQDEyBHbG9iYWxTaWduIEdDQyBSMyBEViBUTFMgQ0EgMjAy
MDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKxnlJV/de+OpwyvCXAJ
IcxPCqkFPh1lttW2oljS3oUqPKq8qX6m7K0OVKaKG3GXi4CJ4fHVUgZYE6HRdjqj
hhnuHY6EBCBegcUFgPG0scB12Wi8BHm9zKjWxo3Y2bwhO8Fvr8R42pW0eINc6OTb
QXC0VWFCMVzpcqgz6X49KMZowAMFV6XqtItcG0cMS//9dOJs4oBlpuqX9INxMTGp
6EASAF9cnlAGy/RXkVS9nOLCCa7pCYV+WgDKLTF+OK2Vxw3RUJ/p8009lQeUARv2
UCcNNPCifYX1xIspvarkdjzLwzOdLahDdQbJON58zN4V+lMj0msg+c0KnywPIRp3
BMkCAwEAAaOCAYUwggGBMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEF
BQcDAQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUDZjA
c3+rvb3ZR0tJrQpKDKw+x3wwHwYDVR0jBBgwFoAUj/BLf6guRSSuTVD6Y5qL3uLd
G7wwewYIKwYBBQUHAQEEbzBtMC4GCCsGAQUFBzABhiJodHRwOi8vb2NzcDIuZ2xv
YmFsc2lnbi5jb20vcm9vdHIzMDsGCCsGAQUFBzAChi9odHRwOi8vc2VjdXJlLmds
b2JhbHNpZ24uY29tL2NhY2VydC9yb290LXIzLmNydDA2BgNVHR8ELzAtMCugKaAn
hiVodHRwOi8vY3JsLmdsb2JhbHNpZ24uY29tL3Jvb3QtcjMuY3JsMEcGA1UdIARA
MD4wPAYEVR0gADA0MDIGCCsGAQUFBwIBFiZodHRwczovL3d3dy5nbG9iYWxzaWdu
LmNvbS9yZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAy8j/c550ea86oCkf
r2W+ptTCYe6iVzvo7H0V1vUEADJOWelTv07Obf+YkEatdN1Jg09ctgSNv2h+LMTk
KRZdAXmsE3N5ve+z1Oa9kuiu7284LjeS09zHJQB4DJJJkvtIbjL/ylMK1fbMHhAW
i0O194TWvH3XWZGXZ6ByxTUIv1+kAIql/Mt29PmKraTT5jrzcVzQ5A9jw16yysuR
XRrLODlkS1hyBjsfyTNZrmL1h117IFgntBA5SQNVl9ckedq5r4RSAU85jV8XK5UL
REjRZt2I6M9Po9QL7guFLu4sPFJpwR1sPJvubS2THeo7SxYoNDtdyBHs7euaGcMa
D/fayQ==
-----END CERTIFICATE-----
```

Posteriormente é necessário colocar o ficheiro na máquina do HA, em `/usr/local/share/ca-certificates/GlobalSign_GCC_R3_DV_TLS_CA_2020.crt` e também copiar o certificado para o `cacert.pem` do Python. A localização deste ficheiro muda dependendo do tipo de instalação mas pode ser obtido perguntando ao Python qual é com `python -m certifi`. No meu caso o HA corre em `venv` e o ficheiro está em `/home/hassuser/homeassistant-green-3-11-0/lib/python3.11/site-packages/certifi/cacert.pem`

É ainda necessário correr o comando `sudo update-ca-certificates` para o sistema saber que tem um novo certificado disponível e reiniciar o HA.
```
$ sudo update-ca-certificates
Updating certificates in /etc/ssl/certs...
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

Posteriomente o curl já não se queixa e os erros de SSL nos logs do HA desapareceram:
```
$ curl -I https://www.omie.es
HTTP/2 200
date: Wed, 17 Apr 2024 13:08:10 GMT
content-type: text/html; charset=UTF-8
set-cookie: apgwCORS=1fe9e05987a1818347b021e7a21c81fe; Path=/; SameSite=None; Secure
set-cookie: apgw=1fe9e05987a1818347b021e7a21c81fe; Path=/
server: Apache/2.4.41 (Ubuntu)
cache-control: must-revalidate, no-cache, private
x-drupal-dynamic-cache: MISS
link: <https://www.omie.es/es>; rel="canonical", <https://www.omie.es/es>; rel="shortlink"
x-ua-compatible: IE=edge
content-language: es
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
permissions-policy: interest-cohort=()
expires: Sun, 19 Nov 1978 05:00:00 GMT
x-generator: Drupal 9 (https://www.drupal.org)
balancer_worker_route: 02
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-xss-protection: 1; mode=block
referrer-policy: same-origin
feature-policy: autoplay 'self'; camera 'none'; document-domain 'self'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; microphone 'none'; midi 'none'; payment 'none'; xr-spatial-tracking 'none'
content-security-policy: default-src https: data: 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/
content-security-policy: frame-src https://www.google.com/recaptcha/ https://cdnjs.cloudflare.com/ https://www.youtube.com/
content-security-policy: object-src 'self'
```

**Comment by luuuis** [comment]
> A solução que pareceu mais óbvia foi fazer o download do certificado intermédio em falta GlobalSign GCC R3 DV TLS CA 2020 e instalá-lo na "TrustStore" do sistema e do Python.

Não recomendo, pois toda a "confiança" deve advir dos Root CAs do sistema. Estás de certa forma a adulterar o processo de verificação para o sistema inteiro. O certificado intermédio pode ser descarregado automaticamente ou manualmente para usar na verificação mas não deve ser considerado um Root CA.

<details>

<summary>Exemplo verificação com openssl</summary>

```bash
$ openssl x509 -noout -subject -in cert.pem
subject=CN=www.omie.es
$ openssl verify cert.pem                                  
CN=www.omie.es
error 20 at 0 depth lookup: unable to get local issuer certificate
error cert.pem: verification failed
C0FA22F101000000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:263:calling stat(/opt/homebrew/etc/openssl@3/certs)
$ openssl x509 -noout -text -in cert.pem | grep -A1 "Authority Information Access"
            Authority Information Access: 
                CA Issuers - URI:http://secure.globalsign.com/cacert/gsgccr3dvtlsca2020.crt
$ wget -q http://secure.globalsign.com/cacert/gsgccr3dvtlsca2020.crt
$ openssl verify -untrusted gsgccr3dvtlsca2020.crt cert.pem
cert.pem: OK
```
</details>

O mais correcto será o OMIE corrigir a configuração do servidor. Nota: quem actualizar para o https://github.com/luuuis/hass_omie/releases/tag/v1.0.9 não precisa de se preocupar com nada disto.

**Comment by luuuis** [comment]
A configuração já foi corrigida no www.omie.es, já não é necessário recorrer à v1.0.9.

![SSL Server Test: www omie es (Powered by Qualys SSL Labs) 2024-04-17 17-57-10](https://github.com/luuuis/hass_omie/assets/161006/4ee41884-1bb9-42bb-b82b-841c195183b9)https://www.ssllabs.com/ssltest/analyze.html?d=www.omie.es
