### ISSUE TITLE
Ibelectra Solução Família simples:  erro no APEX

### ISSUE THREAD

**Issue by somar12** [luuuis/hass_omie#66]
Estou a ter dificuldade em colocar a funcionar o script para a IBELECTRA, uma ajuda precisa-se

"// apexcharts-card version 2.0.4 /// value.series is missing value.template is extraneous"

Obrigado

**Comment by luuuis** [comment]
Impossível ajudar só a partir da informação que foi partilhada. Provavelmente fizeste asneira no YAML (em lado algum os gráficos que partilho usam o atributo `template`).

Tens de dizer:
1. O que fizeste (passo a passo)
2. O que esperavas que acontecesse
3. O que aconteceu de facto

Incluir os erros por completo, qual o código utilizado, e por aí fora, pois as minhas capacidades telepáticas têm andado um pouco desafinadas. :)

**Comment by somar12** [comment]
Antes de mais, obrigado pela rápida resposta.

1.  O que fiz:
    - Tenho o OMIE Home Assistant Integration instalado;
    -  Copiei o código do GITHUB relativo à Ibelectra simples e coloquei-o num “cartão” Apexcharts.
    template:
  sensor:
    - unique_id: ibelectra_familia_simples
      unit_of_measurement: €/MWh
      availability: '{{ state_attr(''sensor.omie_spot_price_pt'', ''today_average'') != None }}'
      state_class: measurement
      state: >
        {% set OMIE = state_attr('sensor.omie_spot_price_pt', 'today_average')
        -%} {% set CGS = state_attr(this.entity_id, 'CGS') -%} {% set Perdas =
        state_attr(this.entity_id, 'Perdas') -%} {% set k =
        state_attr(this.entity_id, 'k') -%} {% set TAR =
        state_attr(this.entity_id, 'TAR') -%}

        {% if None in [CGS, Perdas, k, TAR] %}
          {{ None }}
        {% else %}
          {{ ((OMIE+CGS)*(1+Perdas)+k+TAR) | round(2) }}
        {% endif %}
      attributes:
        friendly_name: Ibelectra Solução Familia (tarifário simples)
        formula: (OMIE+CGS)*(1+Perdas)+k+TAR
        OMIE: '{{ state_attr(''sensor.omie_spot_price_pt'', ''today_average'') }}'
        CGS: '{{ 7 }}'
        Perdas: '{{ 0.1604 }}'
        k: '{{ 3.5 }}'
        TAR: '{{ 36.50 }}'
        today_hours: >
          {% set OMIE = state_attr('sensor.omie_spot_price_pt', 'today_average')
          -%} {% set CGS = state_attr(this.entity_id, 'CGS') -%} {% set Perdas =
          state_attr(this.entity_id, 'Perdas') -%} {% set k =
          state_attr(this.entity_id, 'k') -%} {% set TAR =
          state_attr(this.entity_id, 'TAR') -%}

          {% set ns = namespace(hourly_data=[]) %} {% for h in
          state_attr('sensor.omie_spot_price_pt', 'today_hours') -%}
            {% if None in [OMIE, CGS, Perdas, k, TAR] %}
              {% set price = None %}
            {% else %}
              {% set price=((OMIE+CGS)*(1+Perdas)+k+TAR) | round(2) %}
            {% endif %}
            {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %}
          {% endfor -%} {{ dict(ns.hourly_data) }}
        tomorrow_hours: >
          {% set OMIE = state_attr('sensor.omie_spot_price_pt',
          'tomorrow_average') -%} {% set CGS = state_attr(this.entity_id, 'CGS')
          -%} {% set Perdas = state_attr(this.entity_id, 'Perdas') -%} {% set k
          = state_attr(this.entity_id, 'k') -%} {% set TAR =
          state_attr(this.entity_id, 'TAR') -%}

          {% set ns = namespace(hourly_data=[]) %} {% for h in
          state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours') -%}
            {% if None in [OMIE, CGS, Perdas, k, TAR] %}
              {% set price=None %}
            {% else %}
              {% set price=((OMIE+CGS)*(1+Perdas)+k+TAR) | round(2) %}
            {% endif %}
            {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %}
          {% endfor -%} {{ dict(ns.hourly_data) }}

2. Esperava ter a informação como cliente Ibelectra dos preços a cobrar pela Ibelectra.

3.O que aconteceu de facto foi ter esta situação:


[O que acontece.pdf](https://github.com/luuuis/hass_omie/files/15284355/O.que.acontece.pdf)


Mais uma vez obrigado.

**Comment by luuuis** [comment]
Ok, bem me parecia que ia para aí alguma salganhada.

Os templates dos tarifários não se utilizam com com o ApexCharts directamente mas sim são configurados no ficheiro `configuration.yaml` do Home Assistant. Portanto deves primeiro perceber como mexer no `configuration.yaml` por format a acrescentar o sensor: basicamente tens de colar lá [o código que eu partilho no wiki](https://github.com/luuuis/hass_omie/wiki/Ibelectra-Solução-Família-simples) tendo o cuidado de manter o espaçamento inalterado. Há inúmeros tutoriais em blogs, YouTube e afins sobre editar o `configuration.yaml`.

Uma vez que tenhas os sensores a funcionar correctamente podes começar a configurar os gráficos com o apexcharts-card se quiseres (não é obrigatório).

**Comment by somar12** [comment]
Obrigado.
