### ISSUE TITLE
[Enhancement] Possibility to choose final sensor units (€/MWh vs €/kWh)

### ISSUE THREAD

**Issue by FragMenthor** [luuuis/hass_omie#8]
Add a "toggle option" ou similar to choose the format of the resulting sensors, avoiding doing templates to convert for normal final user units (€/kWh). And thanks for your integration! :)

**Comment by luuuis** [comment]
Hi,

Can you explain where you are using the sensors that you'd like to see the €/kWh value? The first prototype did in fact use`€/kWh` but I found it just caused an extra `0.0` prefix on everything, which is not terribly useful and takes up more space that may not be available on mobile. For example, the following card would no longer accommodate values such as `0.02959` for lack of horizontal space.

![Home Assistant - Home – Home Assistant 2023-03-13 11-43-15](https://user-images.githubusercontent.com/161006/224692425-919fe149-f878-419c-9cdb-f27ea964c7cc.jpg)

Ideally Home Assistant would be able to [convert the unit of measurement in the sensor settings](https://www.home-assistant.io/blog/2022/04/06/release-20224/#adjusting-unit-of-measurement-for-sensors) without needing to change anything in the sensor implementation but currently this is only supported for temperature and pressure. This would be my preferred approach. This sort of conversion is already happening in the Energy dashboard when Home Assistant shows costs per kWh even if the sensor is about MWh.

![Home Assistant - Energy – Home Assistant 2023-03-13 11-55-06](https://user-images.githubusercontent.com/161006/224694845-ab2f154d-319a-4edc-8c83-7f5f04246800.jpg)

For now I suggest these workarounds:

1. For display inside Entities Cards you could use https://github.com/benct/lovelace-multiple-entity-row with the `format: kilo` option. This rounds to two decimal places as well.
  ![Home – Home Assistant 2023-03-13 11-46-39](https://user-images.githubusercontent.com/161006/224693125-f5894d9e-cd4c-4b45-b0cc-e8482e7d7532.jpg)

2. Similarly, for graphs I recommend [ApexCharts](https://github.com/RomRider/apexcharts-card#transform-option) that allows dividing by 1000 using `transform: "return x / 1000;"`.

3. Finally, in template sensors that calculate final costs (such as those in [Wiki: Coopérnico Base](https://github.com/luuuis/hass_omie/wiki/Coop%C3%A9rnico-Base)) you would, of course, continue to do the conversion inline.

**Comment by FragMenthor** [comment]
Ok I understand. I also use that method for others sensors, and in fact I must also use templates to calculate prices for my provider. So, thanks again, and closed!
